#!/bin/bash
source "$ROOT_PATH/recipes/essentials"
source "$LIB_PATH/ruby.sh"
source "$LIB_PATH/nodejs.sh"
source "$LIB_PATH/mysql.sh"

function install_app {
  load_essentials_conf

  install_mysql_client
  install_ruby_rbenv
  install_java
  install_nodejs
  install_rbenv_bundler
  install_rbenv_gems
  install_monit
}
