#!/bin/bash
source "$ROOT_PATH/recipes/essentials"
source "$LIB_PATH/ruby.sh"
source "$LIB_PATH/nodejs.sh"
source "$LIB_PATH/mysql.sh"
source "$LIB_PATH/memcache.sh"

function install_app {
  load_essentials_conf
  install_mysql_client
  # install_ruby
  # install_bundler
  # install_gems
  install_java
  install_nodejs
  install_monit
  # install_memcache
}
