#!/bin/bash
source "$LIB_PATH/utils.sh"
source "$LIB_PATH/hostname.sh"
source "$LIB_PATH/user.sh"
source "$LIB_PATH/security.sh"

function load_essentials_conf {
  #TODO: verify if vars are set and then use defautls our get 'em another way
  HOST_NAME="myhost"
  USER_NAME="app"
  USER_PASSWORD="apps3cr3t"
  USER_SSH_KEY="copy and paste your ~/.ssh/id_rsa.pub"
  LOG_FILE="../install.log"
}

function install_essentials {
  load_essentials_conf

  upgrade_system
  make_sure_no_apache
  install_basics
  install_ntp
  install_java
  update_locale_en_US_UTF_8
  additional_installs
  set_hostname $HOST_NAME
  update_locale_en_US_UTF_8
  create_deploy_user $USER_NAME $USER_PASSWORD "$USER_SSH_KEY"
  set_basic_security
}
